version: '3'

services:

  server:
    container_name: todolist_server
    image: nginx:1.15-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/www/html
      - ./docker/server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: todolist_app
    build: ./docker/app
    user: 501:501
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  database:
    container_name: todolist_database
    build: ./docker/database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/databases:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
